export const cardData = {
    'Gravação': [
      {
        title: 'Gravação - Card 1',
        favorite: false,
        added: false,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 1 - Descrição para esse card!',
      },
      {
        title: 'Gravação - Card 2',
        favorite: true,
        added: true,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 2 - Descrição para esse card!',
      },
      {
        title: 'Gravação - Card 3',
        favorite: false,
        added: false,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 3 - Descrição para esse card!',
      },
      {
        title: 'Gravação - Card 4',
        favorite: true,
        added: true,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 4 - Descrição para esse card!',
      },
      {
        title: 'Gravação - Card 5',
        favorite: true,
        added: false,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 5 - Descrição para esse card!',
      },
    ],
    'EPIs': [
      {
        title: 'EPIs - Card 1',
        favorite: false,
        added: false,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 1 - Descrição para esse card!',
      },
      {
        title: 'EPIs - Card 2',
        favorite: true,
        added: true,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 2 - Descrição para esse card!',
      },
      {
        title: 'EPIs - Card 3',
        favorite: false,
        added: false,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 3 - Descrição para esse card!',
      },
      {
        title: 'EPIs - Card 4',
        favorite: true,
        added: true,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 4 - Descrição para esse card!',
      },
      {
        title: 'EPIs - Card 5',
        favorite: true,
        added: false,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 5 - Descrição para esse card!',
      },
    ],
    'Cortes': [
        {
          title: 'Cortes - Card 1',
          favorite: false,
          added: false,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 1 - Descrição para esse card!',
        },
        {
          title: 'Cortes - Card 2',
          favorite: true,
          added: true,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 2 - Descrição para esse card!',
        },
        {
          title: 'Cortes - Card 3',
          favorite: false,
          added: false,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 3 - Descrição para esse card!',
        },
        {
          title: 'Cortes - Card 4',
          favorite: true,
          added: true,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 4 - Descrição para esse card!',
        },
        {
          title: 'Cortes - Card 5',
          favorite: true,
          added: false,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 5 - Descrição para esse card!',
        },
      ],
      'Teclados': [
        {
          title: 'Teclados - Card 1',
          favorite: false,
          added: false,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 1 - Descrição para esse card!',
        },
        {
          title: 'Teclados - Card 2',
          favorite: true,
          added: true,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 2 - Descrição para esse card!',
        },
        {
          title: 'Teclados - Card 3',
          favorite: false,
          added: false,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 3 - Descrição para esse card!',
        },
        {
          title: 'Teclados - Card 4',
          favorite: true,
          added: true,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 4 - Descrição para esse card!',
        },
        {
          title: 'Teclados - Card 5',
          favorite: true,
          added: false,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 5 - Descrição para esse card!',
        },
      ],
    // Repita o mesmo padrão para outras categorias
  };
  