export const cardData = {
    'Gravação': [
      {
        title: 'Serviços e Produtos com Gravação a Laser Fibra',
        favorite: false,
        added: false,
        imageSrc: 'https://www.lasermax.com.br/wp-content/uploads/2020/06/gravacao-a-laser2.png',
        description: 'Executamos serviços ou desenvolvemos produtos com Gravação a Laser personalizada, Materiais aceitos para gravação: Metais (Alumínio e Aço), Plásticos, Madeiras, Couros e Tecidos.',
      },
      {
        title: 'Serviços e Produtos com Corte, Gravação a Laser CO2 (Metal)',
        favorite: true,
        added: true,
        imageSrc: 'https://www.lasermax.com.br/wp-content/uploads/2020/06/gravacao-laser2.png',
        description: 'Executamos serviços ou desenvolvemos produtos com Corte e Gravação a Laser CO2 personalizada. Corte em Acrílico, Madeiras (MDF), Aço plano, Plásticos, Tecidos e Couro. Gravação em Acrílico, Madeiras, Vidros, Couro, Tecidos, Espelhos e Metais (alguns).',
      },
      {
        title: 'Gravação - Card 3',
        favorite: false,
        added: false,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 3 - Descrição para esse card!',
      },
      {
        title: 'Gravação - Card 4',
        favorite: true,
        added: true,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 4 - Descrição para esse card!',
      },
      {
        title: 'Gravação - Card 5',
        favorite: true,
        added: false,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 5 - Descrição para esse card!',
      },
    ],
    'EPIs': [
      {
        title: 'EPIs - Card 1',
        favorite: false,
        added: false,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 1 - Descrição para esse card!',
      },
      {
        title: 'EPIs - Card 2',
        favorite: true,
        added: true,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 2 - Descrição para esse card!',
      },
      {
        title: 'EPIs - Card 3',
        favorite: false,
        added: false,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 3 - Descrição para esse card!',
      },
      {
        title: 'EPIs - Card 4',
        favorite: true,
        added: true,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 4 - Descrição para esse card!',
      },
      {
        title: 'EPIs - Card 5',
        favorite: true,
        added: false,
        imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
        description: 'Card 5 - Descrição para esse card!',
      },
    ],
    'Cortes': [
        {
          title: 'Cortes - Card 1',
          favorite: false,
          added: false,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 1 - Descrição para esse card!',
        },
        {
          title: 'Cortes - Card 2',
          favorite: true,
          added: true,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 2 - Descrição para esse card!',
        },
        {
          title: 'Cortes - Card 3',
          favorite: false,
          added: false,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 3 - Descrição para esse card!',
        },
        {
          title: 'Cortes - Card 4',
          favorite: true,
          added: true,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 4 - Descrição para esse card!',
        },
        {
          title: 'Cortes - Card 5',
          favorite: true,
          added: false,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 5 - Descrição para esse card!',
        },
      ],
      'Teclados': [
        {
          title: 'Teclados - Card 1',
          favorite: false,
          added: false,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 1 - Descrição para esse card!',
        },
        {
          title: 'Teclados - Card 2',
          favorite: true,
          added: true,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 2 - Descrição para esse card!',
        },
        {
          title: 'Teclados - Card 3',
          favorite: false,
          added: false,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 3 - Descrição para esse card!',
        },
        {
          title: 'Teclados - Card 4',
          favorite: true,
          added: true,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 4 - Descrição para esse card!',
        },
        {
          title: 'Teclados - Card 5',
          favorite: true,
          added: false,
          imageSrc: 'https://cdn.dooca.store/1286/posts/dreamstime-s-58978412.jpg?v=1632256363&webp=0',
          description: 'Card 5 - Descrição para esse card!',
        },
      ],
    // Repita o mesmo padrão para outras categorias
  };
  